services:
  backend:
    build: ./backend
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DB_HOST: db
      DB_NAME: job_scrapper
      FRONTEND_URL: http://frontend:3000
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - job-scraper

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
#    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend/app:/app
    restart: always
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - job-scraper

#  ollama:
#    build:
#      context: ./ollama
#      dockerfile: ollama.dockerfile
#    ports:
#      - "11434:11434"
#    volumes:
#      - ./ollama:/root/.ollama
#    container_name: ollama
#    tty: true
#    restart: unless-stopped
#    networks:
#      - job-scraper

  ai:
    build: ./ai
    ports:
      - "5001:5001"
    volumes:
      - ./ai:/app
    networks:
      - job-scraper

#  ai-service:
#    build: ./ai-service
#    volumes:
#      - ./ai-service:/app
#    ports:
#      - "3000:3000"
#    networks:
#      - job-scraper

#  llama:
#    image: ghcr.io/ggerganov/llama.cpp:full
#    command: [ "--run", "./models/mistral-7b-instruct.Q5_K_M.gguf", "--host", "0.0.0.0", "--port", "8001" ]
#    ports:
#      - "8001:8001"
#    volumes:
#      - ./models:/models
#    networks:
#      - job-scraper

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_scrapper
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
        - "3306:3306"
    volumes:
        - ./db:/var/lib/mysql
    networks:
      - job-scraper
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - job-scraper

volumes:
    db:

networks:
  job-scraper:
